import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import api from '../utils/api';

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

const formatINR = (amt) => '₹' + new Intl.NumberFormat('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amt || 0);

const formatMethod = (m) => ({ cash: 'Cash', upi: 'UPI', bank_transfer: 'Bank Transfer', cheque: 'Cheque', online: 'Online' }[m] || m || 'Cash');

const numberToWords = (num) => {
  if (!num || num === 0) return 'Zero';
  const ones = ['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];
  const tens = ['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];
  const n = Math.floor(num);
  let str = '';
  if (n >= 10000000) str += numberToWords(Math.floor(n/10000000)) + ' Crore ';
  const r1 = n % 10000000;
  if (r1 >= 100000) str += numberToWords(Math.floor(r1/100000)) + ' Lakh ';
  const r2 = r1 % 100000;
  if (r2 >= 1000) str += numberToWords(Math.floor(r2/1000)) + ' Thousand ';
  const r3 = r2 % 1000;
  if (r3 >= 100) str += ones[Math.floor(r3/100)] + ' Hundred ';
  const r4 = r3 % 100;
  if (r4 > 0) { if (str) str += 'and '; if (r4 < 20) str += ones[r4]; else str += tens[Math.floor(r4/10)] + (r4%10 ? ' ' + ones[r4%10] : ''); }
  return str.trim();
};

const ReceiptView = () => {
  const { paymentId } = useParams();
  const { user } = useAuth();
  const { theme } = useTheme();
  const navigate = useNavigate();
  const receiptRef = useRef(null);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => { fetchReceipt(); }, [paymentId]);

  const fetchReceipt = async () => {
    try {
      const result = await api.get(`/api/payments/${paymentId}/details`);
      setData(result);
    } catch (err) {
      console.error('Receipt fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = async () => {
    setDownloading(true);
    try {
      const p = data.payment;
      await api.download(`/api/payments/${paymentId}/receipt`, `Receipt_${MONTHS[p.month-1]}_${p.year}_${data.flat?.number || ''}.pdf`);
    } catch (err) {
      alert(err.message);
    } finally {
      setDownloading(false);
    }
  };

  const handleShareWhatsApp = () => {
    if (!data) return;
    const p = data.payment;
    const s = data.society;
    const f = data.flat;
    const total = (p.amount || 0) + (p.lateFee || 0);
    const text = `🧾 *MAINTENANCE RECEIPT*\n\n🏢 *${s.name}*\n${s.address || ''}\n\n👤 *${f.ownerName}*\n🏠 Block ${f.blockId?.name || ''} - Flat ${f.number}\n📅 ${MONTHS[p.month-1]} ${p.year}\n\n💰 *Amount: ${formatINR(total)}*\n📋 Status: ✅ PAID\n🔖 Receipt: ${p.receiptNumber || p._id.slice(-8).toUpperCase()}\n📆 Date: ${new Date(p.paidDate || p.updatedAt).toLocaleDateString('en-IN')}\n\n_Generated by SocietySync_\n_Powered by Funkariya_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) return <div className="page-loader"><div className="spinner"></div></div>;
  if (!data) return <div className="empty-state"><h2>Receipt not found</h2><button className="btn btn--primary" onClick={() => navigate(-1)}>Go Back</button></div>;

  const { payment: p, society: s, flat: f } = data;
  const total = (p.amount || 0) + (p.lateFee || 0);
  const paidDate = p.paidDate ? new Date(p.paidDate) : new Date(p.updatedAt);
  const receiptNo = p.receiptNumber || `RCP-${p._id.slice(-8).toUpperCase()}`;
  const blockName = f?.blockId?.name || '';
  const flatLabel = blockName ? `${blockName} - ${f.number}` : f?.number;

  return (
    <div className="receipt-page">
      {/* Back button - hide on print */}
      <div className="receipt-actions-top no-print">
        <button className="btn btn--ghost btn--sm" onClick={() => navigate(-1)}>← Back</button>
      </div>

      {/* The receipt card */}
      <div className="receipt-card" ref={receiptRef} id="receipt-printable">

        {/* ─── WATERMARK ─── */}
        {p.status === 'paid' && <div className="receipt-watermark">PAID</div>}

        {/* ─── SOCIETY HEADER ─── */}
        <div className="receipt-header">
          <div className="receipt-header__brand">
            <div className="receipt-header__logo">{s.logo ? <img src={s.logo} alt="" /> : '🏢'}</div>
            <div>
              <h1 className="receipt-header__name">{s.name}</h1>
              <p className="receipt-header__address">
                {[s.address, s.city, s.state, s.pincode].filter(Boolean).join(', ')}
              </p>
              {s.contactNumber && <p className="receipt-header__contact">📞 +91 {s.contactNumber}</p>}
            </div>
          </div>
          <div className="receipt-header__badge">
            <span className={`receipt-status receipt-status--${p.status}`}>
              {p.status === 'paid' ? '✅ PAID' : p.status === 'partial' ? '🔶 PARTIAL' : '⏳ PENDING'}
            </span>
          </div>
        </div>

        {/* ─── TITLE BAR ─── */}
        <div className="receipt-title-bar">
          <span>MAINTENANCE RECEIPT</span>
        </div>

        {/* ─── RECEIPT META ─── */}
        <div className="receipt-meta" style={{ display: 'table', width: '100%', borderCollapse: 'collapse' }}>
          <div style={{ display: 'table-row' }}>
            <div style={{ display: 'table-cell', width: '50%', padding: '10px 20px' }}>
              <span className="receipt-meta__label">Receipt No.</span>
              <span className="receipt-meta__value receipt-meta__mono" style={{ display: 'block' }}>{receiptNo}</span>
            </div>
            <div style={{ display: 'table-cell', width: '50%', padding: '10px 20px', textAlign: 'right' }}>
              <span className="receipt-meta__label">Date</span>
              <span className="receipt-meta__value" style={{ display: 'block' }}>{paidDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</span>
            </div>
          </div>
          {p.transactionId && (
            <div style={{ display: 'table-row' }}>
              <div style={{ display: 'table-cell', padding: '10px 20px' }} colSpan={2}>
                <span className="receipt-meta__label">Transaction ID</span>
                <span className="receipt-meta__value receipt-meta__mono" style={{ display: 'block' }}>{p.transactionId}</span>
              </div>
            </div>
          )}
        </div>

        {/* ─── MEMBER INFO ─── */}
        <div className="receipt-member">
          <h3 className="receipt-section-label">Received with thanks from</h3>
          <div className="receipt-member__info">
            <div className="receipt-member__avatar">{(f?.ownerName || 'U')[0].toUpperCase()}</div>
            <div>
              <h2 className="receipt-member__name">{f?.ownerName || 'N/A'}</h2>
              <div className="receipt-member__badges">
                <span className="receipt-badge receipt-badge--primary">FLAT: {flatLabel}</span>
                <span className="receipt-badge receipt-badge--secondary">PERIOD: {MONTHS[p.month-1]} {p.year}</span>
              </div>
              {f?.ownerPhone && <p className="receipt-member__phone">📱 +91 {f.ownerPhone}</p>}
            </div>
          </div>
        </div>

        {/* ─── PAYMENT TABLE ─── */}
        <div className="receipt-table-wrap">
          <table className="receipt-table">
            <thead>
              <tr>
                <th className="receipt-table__sn">#</th>
                <th>Description</th>
                <th className="receipt-table__amt">Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={{ textAlign: 'center' }}>1</td>
                <td>Maintenance Charges ({MONTHS[p.month-1]} {p.year})</td>
                <td className="receipt-table__amt" style={{ textAlign: 'right' }}>{formatINR(p.amount)}</td>
              </tr>
              <tr>
                <td style={{ textAlign: 'center' }}>2</td>
                <td>Late Fee / Penalty</td>
                <td className="receipt-table__amt" style={{ textAlign: 'right' }}>{p.lateFee > 0 ? formatINR(p.lateFee) : 'Rs. 0.00'}</td>
              </tr>
              <tr>
                <td style={{ textAlign: 'center' }}>3</td>
                <td>Other Charges</td>
                <td className="receipt-table__amt" style={{ textAlign: 'right' }}>Rs. 0.00</td>
              </tr>
            </tbody>
            <tfoot>
              <tr className="receipt-table__total">
                <td colSpan={2} style={{ textAlign: 'right', paddingRight: '20px' }}>TOTAL AMOUNT</td>
                <td style={{ textAlign: 'right' }}>{formatINR(total)}</td>
              </tr>
            </tfoot>
          </table>
        </div>

        {/* ─── AMOUNT IN WORDS ─── */}
        <div className="receipt-words">
          <span className="receipt-words__label">Amount in words:</span>
          <span className="receipt-words__text">Rupees {numberToWords(total)} Only</span>
        </div>

        {/* ─── PAYMENT INFO CARDS ─── */}
        <div className="receipt-info-grid">
            <div>
              <span className="receipt-info-card__label">Payment Mode</span>
              <span className="receipt-info-card__value">{formatMethod(p.paymentMethod)}</span>
            </div>
          <div className="receipt-info-card">
            <div>
              <span className="receipt-info-card__label">Amount Paid</span>
              <span className="receipt-info-card__value receipt-info-card__value--success">{formatINR(p.paidAmount || total)}</span>
            </div>
          </div>
          <div className="receipt-info-card">
            <div>
              <span className="receipt-info-card__label">Status</span>
              <span className={`receipt-info-card__value receipt-info-card__value--${p.status === 'paid' ? 'success' : p.status === 'partial' ? 'warning' : 'danger'}`}>
                {(p.status || 'paid').toUpperCase()}
              </span>
            </div>
          </div>
        </div>

        {/* ─── NOTES ─── */}
        {p.notes && (
          <div className="receipt-notes">
            <span className="receipt-notes__label">Notes</span>
            <p>{p.notes}</p>
          </div>
        )}

        {/* ─── QR + SIGNATURE ─── */}
        <div className="receipt-bottom">
          <div className="receipt-qr">
            <div className="receipt-qr__box">
              <img 
                src={`https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(`Receipt:${receiptNo}|Amount:${total}|Date:${paidDate.toISOString()}|Society:${s.name}`)}`} 
                alt="QR Code" 
                width="100" 
                height="100"
              />
            </div>
            <span className="receipt-qr__label">Scan to verify</span>
          </div>
          <div className="receipt-signature">
            <div className="receipt-signature__line"></div>
            <span>Authorized Signatory</span>
          </div>
        </div>

        {/* ─── FOOTER ─── */}
        <div className="receipt-footer">
          <div className="receipt-footer__notes">
            <p>1. Maintenance should be paid between 1st - 10th of every month.</p>
            <p>2. This is a computer-generated receipt and does not require a physical signature.</p>
          </div>
          <div className="receipt-footer__brand">
            <span>Generated by <strong>SocietySync</strong></span>
            <span>Powered by <strong>Funkariya</strong></span>
          </div>
        </div>
      </div>

      {/* ─── ACTION BUTTONS (below card) ─── */}
      <div className="receipt-actions no-print">
        <button className="receipt-action-btn receipt-action-btn--download" onClick={handleDownloadPDF} disabled={downloading}>
          {downloading ? <span className="btn-spinner"></span> : '📥'} Download PDF
        </button>
        <button className="receipt-action-btn receipt-action-btn--whatsapp" onClick={handleShareWhatsApp}>
          📲 Share on WhatsApp
        </button>
        <button className="receipt-action-btn receipt-action-btn--print" onClick={handlePrint}>
          🖨️ Print Receipt
        </button>
      </div>
    </div>
  );
};

export default ReceiptView;
