import type { Client, Task, Activity, AISuggestion, DashboardStats, Notification, Reminder, AnalyticsData, StaffWorkload } from "@/types";

export const DEMO_CLIENTS: Client[] = [
  {
    id: "c1",
    name: "Ramesh Industries Pvt Ltd",
    email: "ramesh@industry.com",
    phone: "+91 98765 10001",
    whatsapp: "+91 98765 10001",
    gstNumber: "27AAACH1234P1Z5",
    panNumber: "AAACH1234P",
    businessType: "private_ltd",
    businessName: "Ramesh Industries Pvt Ltd",
    address: "123 Industrial Area, Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400069",
    healthScore: 85,
    riskLevel: "low",
    status: "active",
    createdAt: new Date("2023-06-15"),
    lastActivity: new Date("2024-12-28"),
    notes: "Key client - Manufacturing unit",
    documents: [
      { id: "d1", clientId: "c1", type: "gstr1", name: "GSTR-1 November 2024", status: "verified", requiredFor: ["gst"], uploadedAt: new Date("2024-12-05"), verifiedAt: new Date("2024-12-06") },
      { id: "d2", clientId: "c1", type: "gstr3b", name: "GSTR-3B November 2024", status: "received", requiredFor: ["gst"], uploadedAt: new Date("2024-12-10") },
      { id: "d3", clientId: "c1", type: "bank_statement", name: "Bank Statement Nov 2024", status: "pending", requiredFor: ["gst", "itr"] },
    ],
    filings: [
      { id: "f1", clientId: "c1", type: "gst", period: "November 2024", dueDate: new Date("2025-01-11"), status: "in_progress" },
      { id: "f2", clientId: "c1", type: "itr", period: "FY 2023-24", dueDate: new Date("2025-01-31"), status: "pending" },
    ],
    payments: [
      { id: "p1", clientId: "c1", amount: 15000, type: "filing", status: "paid", dueDate: new Date("2024-12-15"), paidAt: new Date("2024-12-14"), method: "upi" },
      { id: "p2", clientId: "c1", amount: 25000, type: "filing", status: "pending", dueDate: new Date("2025-01-15"), method: "upi" },
    ],
  },
  {
    id: "c2",
    name: "Sharma Trading Company",
    email: "sharma.trading@email.com",
    phone: "+91 98765 10002",
    whatsapp: "+91 98765 10002",
    gstNumber: "19AAACH5678Q2Z8",
    panNumber: "AAACH5678Q",
    businessType: "proprietorship",
    businessName: "Sharma Trading Company",
    address: "45 Market Road, Salt Lake",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700064",
    healthScore: 45,
    riskLevel: "high",
    status: "active",
    createdAt: new Date("2023-09-20"),
    lastActivity: new Date("2024-12-15"),
    notes: "Frequently delays document submission",
    documents: [
      { id: "d4", clientId: "c2", type: "gstr1", name: "GSTR-1 October 2024", status: "pending", requiredFor: ["gst"] },
      { id: "d5", clientId: "c2", type: "bank_statement", name: "Bank Statement Oct 2024", status: "rejected", requiredFor: ["gst", "itr"], notes: "Statement incomplete" },
    ],
    filings: [
      { id: "f3", clientId: "c2", type: "gst", period: "October 2024", dueDate: new Date("2024-11-30"), status: "overdue" },
      { id: "f4", clientId: "c2", type: "itr", period: "FY 2023-24", dueDate: new Date("2024-01-31"), status: "filed", filedAt: new Date("2024-03-15"), acknowledgmentNumber: "ITR-A-2024-12345" },
    ],
    payments: [
      { id: "p3", clientId: "c2", amount: 8000, type: "filing", status: "overdue", dueDate: new Date("2024-11-30") },
    ],
  },
  {
    id: "c3",
    name: "Tech Solutions LLP",
    email: "contact@techsol.in",
    phone: "+91 98765 10003",
    whatsapp: "+91 98765 10003",
    gstNumber: "29AABCT1234R1Z9",
    panNumber: "AABCT1234R",
    businessType: "llp",
    businessName: "Tech Solutions LLP",
    address: "78 Tech Park, Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560066",
    healthScore: 92,
    riskLevel: "low",
    status: "active",
    createdAt: new Date("2022-03-10"),
    lastActivity: new Date("2025-01-02"),
    notes: "Software development company - Excellent compliance",
    documents: [
      { id: "d6", clientId: "c3", type: "gstr1", name: "GSTR-1 December 2024", status: "verified", requiredFor: ["gst"], uploadedAt: new Date("2025-01-05"), verifiedAt: new Date("2025-01-06") },
      { id: "d7", clientId: "c3", type: "gstr3b", name: "GSTR-3B December 2024", status: "verified", requiredFor: ["gst"], uploadedAt: new Date("2025-01-08"), verifiedAt: new Date("2025-01-08") },
      { id: "d8", clientId: "c3", type: "itr_form", name: "ITR Form FY 2023-24", status: "verified", requiredFor: ["itr"], uploadedAt: new Date("2024-07-20"), verifiedAt: new Date("2024-07-21") },
    ],
    filings: [
      { id: "f5", clientId: "c3", type: "gst", period: "December 2024", dueDate: new Date("2025-01-11"), status: "filed", filedAt: new Date("2025-01-10"), acknowledgmentNumber: "GSTR-2025-1234567" },
    ],
    payments: [
      { id: "p4", clientId: "c3", amount: 35000, type: "filing", status: "paid", dueDate: new Date("2024-12-20"), paidAt: new Date("2024-12-18"), method: "bank_transfer" },
    ],
  },
  {
    id: "c4",
    name: "Mehta & Associates",
    email: "mehta.ca@ gmail.com",
    phone: "+91 98765 10004",
    whatsapp: "+91 98765 10004",
    gstNumber: "22AABCM9876S2Z4",
    panNumber: "AABCM9876S",
    businessType: "partnership",
    businessName: "Mehta & Associates",
    address: "12 Law Chambers, Crawford Market",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400001",
    healthScore: 68,
    riskLevel: "medium",
    status: "active",
    createdAt: new Date("2023-01-25"),
    lastActivity: new Date("2024-12-20"),
    documents: [
      { id: "d9", clientId: "c4", type: "balance_sheet", name: "Balance Sheet FY 2023-24", status: "received", requiredFor: ["itr", "audit"] },
    ],
    filings: [
      { id: "f6", clientId: "c4", type: "audit", period: "FY 2023-24", dueDate: new Date("2025-02-28"), status: "in_progress" },
      { id: "f7", clientId: "c4", type: "tds", period: "Q4 FY 2024-25", dueDate: new Date("2025-01-31"), status: "pending" },
    ],
    payments: [],
  },
  {
    id: "c5",
    name: "Patel Retail Store",
    email: "patel.retail@email.com",
    phone: "+91 98765 10005",
    whatsapp: "+91 98765 10005",
    gstNumber: "24AABCP5432T1Z7",
    panNumber: "AABCP5432T",
    businessType: "proprietorship",
    businessName: "Patel Retail Store",
    address: "67 Main Road, Navsari",
    city: "Navsari",
    state: "Gujarat",
    pincode: "396445",
    healthScore: 30,
    riskLevel: "high",
    status: "inactive",
    createdAt: new Date("2023-11-05"),
    lastActivity: new Date("2024-10-15"),
    notes: "Client not responding to calls for 2 months",
    documents: [
      { id: "d10", clientId: "c5", type: "gstr1", name: "GSTR-1 September 2024", status: "pending", requiredFor: ["gst"] },
      { id: "d11", clientId: "c5", type: "gstr3b", name: "GSTR-3B September 2024", status: "pending", requiredFor: ["gst"] },
      { id: "d12", clientId: "c5", type: "bank_statement", name: "Bank Statement Sep 2024", status: "pending", requiredFor: ["gst", "itr"] },
    ],
    filings: [
      { id: "f8", clientId: "c5", type: "gst", period: "September 2024", dueDate: new Date("2024-10-31"), status: "overdue" },
      { id: "f9", clientId: "c5", type: "gst", period: "October 2024", dueDate: new Date("2024-11-30"), status: "overdue" },
      { id: "f10", clientId: "c5", type: "gst", period: "November 2024", dueDate: new Date("2024-12-31"), status: "overdue" },
    ],
    payments: [
      { id: "p5", clientId: "c5", amount: 12000, type: "filing", status: "overdue", dueDate: new Date("2024-09-30") },
      { id: "p6", clientId: "c5", amount: 15000, type: "filing", status: "overdue", dueDate: new Date("2024-10-31") },
    ],
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: "t1",
    title: "File GSTR-1 for Ramesh Industries",
    description: "Monthly GST return filing for November 2024",
    clientId: "c1",
    assignedTo: "2",
    assignedBy: "1",
    status: "in_progress",
    priority: "high",
    dueDate: new Date("2025-01-11"),
    filingType: "gst",
    createdAt: new Date("2024-12-20"),
  },
  {
    id: "t2",
    title: "Prepare ITR for Tech Solutions LLP",
    description: "Income Tax Return for Financial Year 2023-24",
    clientId: "c3",
    assignedTo: "2",
    assignedBy: "1",
    status: "completed",
    priority: "medium",
    dueDate: new Date("2024-07-31"),
    filingType: "itr",
    completedAt: new Date("2024-07-25"),
    createdAt: new Date("2024-06-15"),
  },
  {
    id: "t3",
    title: "Follow up with Sharma Trading",
    description: "Documents are pending since 15 days",
    clientId: "c2",
    assignedTo: "2",
    assignedBy: "1",
    status: "delayed",
    priority: "urgent",
    dueDate: new Date("2024-12-25"),
    filingType: "gst",
    createdAt: new Date("2024-12-10"),
  },
  {
    id: "t4",
    title: "Audit planning for Mehta & Associates",
    description: "Start audit procedures for FY 2023-24",
    clientId: "c4",
    assignedTo: "2",
    assignedBy: "1",
    status: "pending",
    priority: "medium",
    dueDate: new Date("2025-01-15"),
    filingType: "audit",
    createdAt: new Date("2024-12-28"),
  },
  {
    id: "t5",
    title: "GSTR-3B correction for Patel Retail",
    description: "Rectify GSTR-3B for July 2024 - Input tax credit error",
    clientId: "c5",
    assignedTo: "2",
    assignedBy: "1",
    status: "pending",
    priority: "low",
    dueDate: new Date("2025-01-20"),
    filingType: "gst",
    createdAt: new Date("2024-12-30"),
  },
];

export const DEMO_ACTIVITIES: Activity[] = [
  { id: "a1", clientId: "c3", userId: "2", type: "document_uploaded", title: "GSTR-3B uploaded", description: "GSTR-3B December 2024 uploaded", createdAt: new Date("2025-01-08") },
  { id: "a2", clientId: "c1", userId: "2", type: "filing_completed", title: "GSTR-1 filed", description: "GSTR-1 November 2024 filed successfully", createdAt: new Date("2024-12-08") },
  { id: "a3", clientId: "c2", userId: "1", type: "reminder_sent", title: "Reminder sent", description: "Document reminder sent via WhatsApp", createdAt: new Date("2024-12-15") },
  { id: "a4", clientId: "c1", userId: "1", type: "client_updated", title: "Client details updated", description: "Updated business address", createdAt: new Date("2024-12-20") },
  { id: "a5", userId: "2", type: "task_created", title: "New task created", description: "GSTR-1 filing assigned to Priya", createdAt: new Date("2024-12-20") },
  { id: "a6", clientId: "c4", userId: "2", type: "document_uploaded", title: "Balance sheet uploaded", description: "FY 2023-24 balance sheet received", createdAt: new Date("2024-12-22") },
  { id: "a7", clientId: "c5", userId: "1", type: "note_added", title: "Client note added", description: "Client not responding - escalated", createdAt: new Date("2024-12-25") },
  { id: "a8", userId: "1", type: "task_completed", title: "Task completed", description: "ITR filing completed for Tech Solutions", createdAt: new Date("2024-07-25") },
];

export const DEMO_AI_SUGGESTIONS: AISuggestion[] = [
  { id: "ai1", type: "client_inactive", title: "Client Inactive for 25 days", description: "Patel Retail Store has not responded to any communication for 25 days. Consider direct visit or calling.", clientId: "c5", priority: "urgent", actionRequired: "Call client immediately", createdAt: new Date() },
  { id: "ai2", type: "deadline_approaching", title: "GST Filing Deadline in 3 days", description: "GSTR-1 for Ramesh Industries is due on January 11th. Ensure all documents are verified.", clientId: "c1", priority: "high", actionRequired: "Verify all documents before filing", createdAt: new Date() },
  { id: "ai3", type: "document_missing", title: "Bank Statement Missing", description: "Bank statement for Sharma Trading (October 2024) was rejected and not re-uploaded.", clientId: "c2", priority: "high", actionRequired: "Request fresh bank statement", createdAt: new Date() },
  { id: "ai4", type: "payment_overdue", title: "Payment Overdue by 45 Days", description: "Patel Retail Store has pending payment of ₹12,000 for the last 45 days.", clientId: "c5", priority: "urgent", actionRequired: "Send payment reminder", createdAt: new Date() },
  { id: "ai5", type: "risk_alert", title: "High Risk Client Alert", description: "Sharma Trading Company has 1 overdue GST filing which may attract penalty.", clientId: "c2", priority: "high", actionRequired: "File pending return immediately", createdAt: new Date() },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  { id: "n1", userId: "1", title: "Document Uploaded", message: "Tech Solutions LLP uploaded GSTR-3B for December 2024", type: "info", read: false, createdAt: new Date() },
  { id: "n2", userId: "1", title: "Task Due Tomorrow", message: "GSTR-1 filing for Ramesh Industries is due tomorrow", type: "warning", read: false, createdAt: new Date() },
  { id: "n3", userId: "1", title: "Payment Received", message: "Received ₹35,000 from Tech Solutions LLP", type: "success", read: true, createdAt: new Date() },
  { id: "n4", userId: "1", title: "Filing Completed", message: "GSTR-1 for November 2024 filed successfully", type: "success", read: true, createdAt: new Date() },
  { id: "n5", userId: "1", title: "Document Rejected", message: "Bank statement for Sharma Trading was rejected", type: "error", read: false, createdAt: new Date() },
];

export const DEMO_REMINDERS: Reminder[] = [
  { id: "r1", clientId: "c2", type: "document", message: "Kindly upload the required documents at your earliest convenience", language: "both", scheduledFor: new Date("2024-12-01"), status: "sent", reminderLevel: 1, createdBy: "1", whatsapp: true },
  { id: "r2", clientId: "c2", type: "document", message: "Return filing may get delayed due to pending documents", language: "both", scheduledFor: new Date("2024-12-05"), status: "sent", reminderLevel: 2, createdBy: "1", whatsapp: true },
  { id: "r3", clientId: "c5", type: "payment", message: "Payment of ₹12,000 is pending. Please clear the dues at earliest", language: "both", scheduledFor: new Date(), status: "scheduled", reminderLevel: 1, createdBy: "1", whatsapp: true },
];

export const DEMO_STAFF_WORKLOAD: StaffWorkload[] = [
  { staffId: "2", staffName: "Priya Patel", activeTasks: 4, completedTasks: 45, delayedTasks: 1 },
  { staffId: "3", staffName: "Rahul Verma", activeTasks: 3, completedTasks: 38, delayedTasks: 0 },
];

export const DEMO_DASHBOARD_STATS: DashboardStats = {
  totalClients: 24,
  pendingDocuments: 12,
  gstDue: 8,
  itrDue: 5,
  pendingPayments: 3,
  staffWorkload: DEMO_STAFF_WORKLOAD,
  urgentAlerts: 4,
  recentActivity: DEMO_ACTIVITIES,
  aiSuggestions: DEMO_AI_SUGGESTIONS,
};

export const DEMO_ANALYTICS: AnalyticsData = {
  monthlyFilings: [
    { month: "Aug", gst: 12, itr: 5, tds: 3, audit: 2 },
    { month: "Sep", gst: 14, itr: 6, tds: 4, audit: 3 },
    { month: "Oct", gst: 15, itr: 4, tds: 3, audit: 2 },
    { month: "Nov", gst: 18, itr: 7, tds: 5, audit: 4 },
    { month: "Dec", gst: 16, itr: 8, tds: 4, audit: 3 },
    { month: "Jan", gst: 14, itr: 6, tds: 3, audit: 2 },
  ],
  clientGrowth: [
    { month: "Aug", new: 2, active: 18, inactive: 3 },
    { month: "Sep", new: 3, active: 20, inactive: 2 },
    { month: "Oct", new: 2, active: 21, inactive: 2 },
    { month: "Nov", new: 1, active: 22, inactive: 1 },
    { month: "Dec", new: 2, active: 23, inactive: 2 },
    { month: "Jan", new: 1, active: 24, inactive: 1 },
  ],
  revenueOverview: [
    { month: "Aug", revenue: 180000, expenses: 45000 },
    { month: "Sep", revenue: 210000, expenses: 52000 },
    { month: "Oct", revenue: 195000, expenses: 48000 },
    { month: "Nov", revenue: 240000, expenses: 55000 },
    { month: "Dec", revenue: 225000, expenses: 58000 },
    { month: "Jan", revenue: 210000, expenses: 50000 },
  ],
  pendingWork: [
    { type: "gst", count: 8, critical: 3 },
    { type: "itr", count: 5, critical: 1 },
    { type: "tds", count: 3, critical: 0 },
    { type: "audit", count: 4, critical: 1 },
  ],
  staffPerformance: [
    { staffId: "2", name: "Priya Patel", tasksCompleted: 45, avgCompletionTime: 3.2, rating: 4.8 },
    { staffId: "3", name: "Rahul Verma", tasksCompleted: 38, avgCompletionTime: 4.1, rating: 4.5 },
  ],
  workloadHeatmap: [
    { day: "Mon", morning: 3, afternoon: 4, evening: 2 },
    { day: "Tue", morning: 4, afternoon: 3, evening: 3 },
    { day: "Wed", morning: 2, afternoon: 5, evening: 2 },
    { day: "Thu", morning: 3, afternoon: 4, evening: 4 },
    { day: "Fri", morning: 4, afternoon: 3, evening: 3 },
    { day: "Sat", morning: 2, afternoon: 2, evening: 1 },
    { day: "Sun", morning: 0, afternoon: 1, evening: 0 },
  ],
};
